valeur = 21
print(f"Le prix est {valeur:.2f} euros")
a = 5
print(f"La valeur est {a} et nous l'avons affichée")
b = 8
print(f"Les valeurs sont {a} et {b}")
print(f"Les valeurs sont {a:10} et {b:10}")
t = f"{a:10}"
type(t)
len(t)
print(f"Les valeurs sont {a:<10} et {b:<10}")
print(f"Les valeurs sont {a:^10} et {b:^10}")
c = 123.12345
print(f"La valeur est {c}")
print(f"La valeur formatée est {c:10.2f}")
print(f"La valeur formatée est {c:.2f}")
print(f"Les valeurs sont {c:<10.2f} et {c:^10.2f} avec alignement")