from django.urls import path
from . import views
from . import api_views

urlpatterns = [
    # Pages web
    path('',
         views.accueil,      name='accueil'),
    path('encoder/',
         views.encoder,      name='encoder'),
    path('decoder/',
         views.decoder,      name='decoder'),
    path('analyser/',
         views.analyser,     name='analyser'),
    path('stats/',
         views.stats,        name='stats'),
    path('historique/',
         views.historique,   name='historique'),
    path('comparaison/',
         views.comparaison,  name='comparaison'),
    path('inscription/',
         views.inscription,  name='inscription'),
    path('connexion/',
         views.connexion,    name='connexion'),
    path('deconnexion/',
         views.deconnexion,  name='deconnexion'),
    path('profil/',
         views.profil,       name='profil'),

    # API REST
    path('api/',
         api_views.api_root,        name='api-root'),
    path('api/encoder/',
         api_views.EncoderAPIView.as_view(),
         name='api-encoder'),
    path('api/decoder/',
         api_views.DecoderAPIView.as_view(),
         name='api-decoder'),
    path('api/analyser/',
         api_views.AnalyserAPIView.as_view(),
         name='api-analyser'),
    path('api/comparer/',
         api_views.ComparerAPIView.as_view(),
         name='api-comparer'),
    path('api/stats/',
         api_views.StatsAPIView.as_view(),
         name='api-stats'),
    path('api/historique/',
         api_views.HistoriqueAPIView.as_view(),
         name='api-historique'),
    path('api/favoris/',
         api_views.FavoriAPIView.as_view(),
         name='api-favoris'),
]