# Generated by Django 6.0.4 on 2026-04-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('texte', models.CharField(max_length=100)),
                ('hex_utf8', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Favori',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('ENCODE', 'Encodage'), ('DECODE', 'Decodage'), ('ANALYSE', 'Analyse'), ('STATS', 'Statistiques')], max_length=10)),
                ('entree', models.TextField()),
                ('sortie', models.TextField()),
                ('nb_chars', models.IntegerField(default=0)),
                ('nb_octets', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historique',
                'ordering': ['-date'],
            },
        ),
    ]
